const data = [
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    //status:"paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-3",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "H-3",
    serv: "Hotel",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-3",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-3",
    serv: "cafe",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-3",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-4",
    serv: "Cafe",
    order: "Sandwich,Chai,Burger",
    customer: "ABC",
    //phone:"",
    total: "90",
    status: "paid",
  },
  {
    id: "R-9",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-4",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-6",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-3",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-3",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-6",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-7",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-7",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "R-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
  {
    id: "C-5",
    serv: "Resturant",
    order: "Sandwich,Juice,Chai,Burger",
    customer: "ABC Sharma",
    phone: "986374690",
    total: "650",
    status: "paid",
  },
];

export { data };
